### ISSUE TITLE
老铁，运行时出现载入log4js日志输出错误

### ISSUE THREAD

**Issue by liwan123123** [binsee/padchat-sdk#101]
C:\Users\lenovo\node_modules\padchat-sdk>node demo.js
载入log4js日志输出配置错误:  TypeError: log4js.configure is not a function
    at Object.<anonymous> (C:\Users\lenovo\node_modules\padchat-sdk\demo.js:23:1
0)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

不知道为何？？

**Comment by binsee** [comment]
如果你要运行内置demo，你需要`git clone`或打包下载然后安装依赖包。
使用`npm i padchat-sdk`安装sdk是用来开发自己的代码的，里边也不会包含`demo.js`。
