### ISSUE TITLE
自动重连功能有时出现“建立ws连接时间间隔过短”问题，导致无法重连

### ISSUE THREAD

**Issue by hawkwithwind** [binsee/padchat-sdk#92]
自动重连功能有时出现“建立wx连接时间间隔过短”问题，导致无法重连。发生这种问题后，只能关闭程序重新登录，需要手工操作，能否在sdk中处理这个问题，让他等待一段时间后重连？这样能降低帐号异常的风险。

```
[2019-02-03T21:00:29.094] [INFO] app - 第 1 次与服务器连接断开！现在将重试连接服务器。
[2019-02-03T21:00:29.152] [ERROR] app - ws 错误: connect ECONNREFUSED 52.82.57.70:8989
[2019-02-03T21:00:29.153] [INFO] app - Websocket已关闭！code: 1006 - 
[2019-02-03T21:00:29.153] [DEBUG] app - 未能连接服务器！将重试连接服务器。
(node:1) UnhandledPromiseRejectionWarning: Error: 建立ws连接时间间隔过短!
    at Padchat.start (/home/work/node_modules/padchat-sdk/index.js:83:13)
    at Padchat.wx.on (/home/work/libs/baseBot.socket.js:103:10)
    at emitTwo (events.js:126:13)
    at Padchat.emit (events.js:214:7)
    at WebSocket.ws.Websocket.on.on.on (/home/work/node_modules/padchat-sdk/index.js:131:14)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/home/work/node_modules/ws/lib/websocket.js:163:12)
    at ClientRequest.req.on (/home/work/node_modules/ws/lib/websocket.js:536:10)
    at emitOne (events.js:116:13)
```

**Comment by binsee** [comment]
请更新至 v0.6.3
